### ISSUE TITLE
Add more TCP ports to Traefik

### ISSUE THREAD

**Issue by cameronelliott** [christippett/terraform-cloudinit-container-server#12]
This is a really cool project.
If I wanted to expose some more tcp ports other than 80,443 would I need to fork this project, or is there some way to tweak the `ports` and `command` sections of `docker-compose.traefik.yaml` without forking?
Thanks,
Cameron

**Comment by christippett** [comment]
Hey, thanks!

If you want to have Traefik load balance services on custom ports, you'd need to override the default Traefik configuration and add entrypoints for the ports you want to expose. Admittedly this would be a bit of a faff and require supplying your own `docker-compose.traefik.yaml` file with the custom configuration, but you wouldn't need to fork the whole project. 

If you don't mind **not** using Traefik, you can reference your own `docker-compose.yaml` and expose whatever ports you want (ensuring the respective firewall ports are also open).

```hcl
module "container-server" {
  source  = "christippett/container-server/cloudinit"
  version = "~> 1.2"

  domain = "example.com"
  email  = "me@example.com"

  files = [
    {
      filename = "docker-compose.yaml"
      content  = filebase64("docker-compose.yaml")
    }
  ]
}
```

```yaml
# docker-compse.yaml

services:
  nginx:
    image: nginx
    container_name: nginx-test
    ports:
      - "8888:80"
```

I'm slowly refactoring how things work that I'll eventually release as version 2. There's a branch to this effect on GitHub ([`feat/v2-wip`](https://github.com/christippett/terraform-cloudinit-container-server/tree/feat/v2-wip)). Rather than having Traefik's configuration hardcoded as command-line arguments in a Docker Compose file, it references an external file and/or environment variables that would make it much easier to override - this would make what you're trying to achieve much less of a hassle. It's mostly ready to go, but if you want to use it today you'd need to fork the branch since it's not yet available from the Terraform registry.

**Comment by cameronelliott** [comment]
Thank you Chris, this is a wonderful project. It seems to really fill a gap for multiple containers on a single VM. Cameron 🙏
